app:
  name: kvm-dashboard
  version: 1.0
  host: localhost
  port: 5001
  mode: debug # debug/release/test

database:
  influxdb:
    url: http://127.0.0.1:8086
    token: ldrl4NwtC-Mq0O-N1VmrKN2jh6WpMzA7fXLKpgpfT0tWWZIlf_Doer84jkWcRwgy6cFzVj2ge_HCZFcA_Xfdkg==
    org: hust
    bucket: kvm-dashboard

rpc:
  server:
    host: localhost
    port: 50001
  client:
    host: localhost
    port: 29090